/* MASTER main.c - paste into Core/Src/main.c (replace existing file)
   Requirements (CubeMX):
   - MX_GPIO_Init(), MX_SPI1_Init(), MX_USART1_UART_Init() present.
   - SPI1: Mode 0, NSS = Software.
   - Ensure pins in gpio.h match your wiring (NSS_Pin, RST_Pin, DIO0_Pin).
*/

#include "main.h"
#include "spi.h"
#include "usart.h"
#include "gpio.h"
#include "LoRa.h"
#include <string.h>
#include <stdio.h>

LoRa myLoRa;
uint8_t rxBuf[128];

/* extern handles generated by CubeMX */
extern SPI_HandleTypeDef hspi1;
extern UART_HandleTypeDef huart1;

/* forward prototypes */
void SystemClock_Config(void);
void Error_Handler(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_USART1_UART_Init();

    HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER BOOT\r\n", 13, 200);

    /* === LoRa object setup === */
    myLoRa = newLoRa();
    myLoRa.CS_port = NSS_GPIO_Port;
    myLoRa.CS_pin  = NSS_Pin;
    myLoRa.reset_port = RST_GPIO_Port;
    myLoRa.reset_pin  = RST_Pin;
    myLoRa.DIO0_port  = DIO0_GPIO_Port;
    myLoRa.DIO0_pin   = DIO0_Pin;
    myLoRa.hSPIx = &hspi1;

    /* radio params (conservative) */
    myLoRa.frequency = 433;
    myLoRa.spredingFactor = SF_7;
    myLoRa.bandWidth = BW_125KHz;
    myLoRa.crcRate = CR_4_5;
    myLoRa.power = POWER_14db;   /* reduce TX power to improve stability */
  //  myLoRa.overCurrentProtection = 120;
    myLoRa.preamble = 8;

    /* Manual reset and quick diagnostic before init */
    HAL_GPIO_WritePin(myLoRa.reset_port, myLoRa.reset_pin, GPIO_PIN_RESET);
    HAL_Delay(10);
    HAL_GPIO_WritePin(myLoRa.reset_port, myLoRa.reset_pin, GPIO_PIN_SET);
    HAL_Delay(50);

    uint8_t ver = LoRa_read(&myLoRa, RegVersion);
    char out[80];
    int n = snprintf(out, sizeof(out), "MASTER: RegVersion=0x%02X\r\n", ver);
    HAL_UART_Transmit(&huart1, (uint8_t*)out, n, 200);

    if (LoRa_init(&myLoRa) == LORA_OK) {
        HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER: LoRa init OK\r\n", 23, 200);
    } else {
        HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER: LoRa init FAIL\r\n", 25, 200);
        /* continue for debug */
    }

    /* Ensure same syncword and modest TX power */
    LoRa_setSyncWord(&myLoRa, 0xF3);
    LoRa_setPower(&myLoRa, POWER_14db);
    LoRa_setOCP(&myLoRa, 120);

    LoRa_startReceiving(&myLoRa);

    /* Example controller packet (32 bytes). Replace with your real 128B packet if needed */
    uint8_t controllerPacket[38];
    for (int i = 0; i < (int)sizeof(controllerPacket); ++i) controllerPacket[i] = (uint8_t)i;

    /* main loop */
    /* MASTER: replace only the while(1) loop body with this */
    /* Replace only the while(1) body in MASTER main.c with this diagnostic loop */

    while (1)
    {
        /* Transmit */
        HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER: TX\r\n", 12, 200);
        uint8_t ok = LoRa_transmit(&myLoRa, controllerPacket, (uint8_t)sizeof(controllerPacket), 1000);
        if (!ok) {
            HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER: TX ERR\r\n", 16, 200);
        }

        /* Immediately enter RX continuous */
        LoRa_startReceiving(&myLoRa);
        uint32_t start = HAL_GetTick();
        int found = 0;

        /* Poll IRQ flag register for up to 2000 ms (print every time it's non-zero) */
        while ((HAL_GetTick() - start) < 2000) {
            uint8_t irq = LoRa_read(&myLoRa, RegIrqFlags);
            /* Print the irq value if non-zero so we can see any flags set */
            if (irq != 0x00) {
                char dbg[80];
                int n = snprintf(dbg, sizeof(dbg), "MASTER: IRQ=0x%02X ts=%lu\r\n", irq, (unsigned long)HAL_GetTick());
                HAL_UART_Transmit(&huart1, (uint8_t*)dbg, n, 200);
            }

            /* RxDone bit = 0x40 */
            if ((irq & 0x40) != 0) {
                /* Clear IRQ flags by writing 0xFF */
                LoRa_write(&myLoRa, RegIrqFlags, 0xFF);

                /* Read number of bytes */
                uint8_t nb = LoRa_read(&myLoRa, RegRxNbBytes);

                /* Read FIFO current addr and set FiFoAddrPtr */
                uint8_t cur = LoRa_read(&myLoRa, RegFiFoRxCurrentAddr);
                LoRa_write(&myLoRa, RegFiFoAddPtr, cur);

                /* Read the payload bytes from FIFO */
                HAL_UART_Transmit(&huart1, (uint8_t*)"MASTER: RX <- (manual read) ", 26, 200);
                for (uint8_t i = 0; i < nb; ++i) {
                    uint8_t b = LoRa_read(&myLoRa, RegFiFo);
                    char tmp[6];
                    int m = snprintf(tmp, sizeof(tmp), "%02X ", b);
                    HAL_UART_Transmit(&huart1, (uint8_t*)tmp, m, 200);
                }
                HAL_UART_Transmit(&huart1, (uint8_t*)"\r\n", 2, 200);

                /* Print RSSI & SNR */
                int rssi = LoRa_getRSSI(&myLoRa);
                int8_t snr = (int8_t)LoRa_read(&myLoRa, RegPktRssiValue /* not SNR reg here */); // quick check
                char info[64];
                int k = snprintf(info, sizeof(info), "MASTER: got packet nb=%u RSSI=%d\r\n", nb, rssi);
                HAL_UART_Transmit(&huart1, (uint8_t*)info, k, 200);

                found = 1;
                break;
            }

            HAL_Delay(10);
        }

        if (!found) {
            char out[64];
            int s = snprintf(out, sizeof(out), "MASTER: no reply ts=%lu (end poll)\r\n", (unsigned long)HAL_GetTick());
            HAL_UART_Transmit(&huart1, (uint8_t*)out, s, 200);
        }

        HAL_Delay(200);
    }

    /* should never reach here */
    return 0;
}

/* ---------- System clock and Error handler ---------- */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) { Error_Handler(); }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) { Error_Handler(); }
}

void Error_Handler(void)
{
  __disable_irq();
  while (1) { }
}
